### ISSUE TITLE
Can not Plug n Play - Pre Trained model or weights from another Pytorch GAN Architecture 

### ISSUE THREAD

**Issue by RohitDhankar** [RohitDhankar/Machine-Learning-with-Python_ML_Py#111]
There is Pytorch  GAN Code from the Git REPO of the Book -- <BOOK NAME > , 
- REPO URL --
- If we try to insert another pre trained Model in place of the model architecture that this particular GAN was trained with -- will get ERRORS as below -- so you can not just Plug n Play - pre trained model or weights from another Architecture - 
```
---type(netG--- <class '__main__.ResNetGenerator'>
---type(model_data--- <class 'collections.OrderedDict'>
Traceback (most recent call last):
  File "/home/dhankar/temp/08_23/pytorch/pytorch_sep23/test_1_CGAN_.py", line 107, in <module>
    netG.load_state_dict(model_data)
  File "/home/dhankar/anaconda3/envs/env2_det2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNetGenerator:
	Unexpected key(s) in state_dict: 
  "model.2.running_mean", 
  "model.2.running_var", 
  "model.2.num_batches_tracked", 
  "model.5.running_mean", "model.5.running_var", 
  "model.5.num_batches_tracked", "model.8.running_mean", 
  "model.8.running_var", "model.8.num_batches_tracked", 
  "model.10.conv_block.2.running_mean", "model.10.conv_block.2.running_var", "model.10.conv_block.2.num_batches_tracked", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.2.running_mean", "model.11.conv_block.2.running_var", "model.11.conv_block.2.num_batches_tracked", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.2.running_mean", "model.12.conv_block.2.running_var", "model.12.conv_block.2.num_batches_tracked", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.2.running_mean", "model.13.conv_block.2.running_var", "model.13.conv_block.2.num_batches_tracked", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.2.running_mean", "model.14.conv_block.2.running_var", "model.14.conv_block.2.num_batches_tracked", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.2.running_mean", "model.15.conv_block.2.running_var", "model.15.conv_block.2.num_batches_tracked", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.2.running_mean", "model.16.conv_block.2.running_var", "model.16.conv_block.2.num_batches_tracked", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.2.running_mean", "model.17.conv_block.2.running_var", "model.17.conv_block.2.num_batches_tracked", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.2.running_mean", "model.18.conv_block.2.running_var", "model.18.conv_block.2.num_batches_tracked", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.18.conv_block.6.num_batches_tracked", "model.20.running_mean", "model.20.running_var", "model.20.num_batches_tracked", "model.23.running_mean", "model.23.running_var", "model.23.num_batches_tracked". 
```

**Comment by RohitDhankar** [comment]
- See how they use the -- state_dict -- This will unwrap your model and optimizer and automatically convert their state_dict for you. 
- https://github.com/Lightning-AI/lightning/blob/cbf2e9d72dcf2054346b810355fee26a0752d235/docs/source-fabric/guide/checkpoint.rst#L94

**Comment by RohitDhankar** [comment]
- Load a PARTIAL STATE DICT | PARTIAL CHECKPOINT -- Ok to load only some 
- - https://github.com/Lightning-AI/lightning/blob/cbf2e9d72dcf2054346b810355fee26a0752d235/docs/source-fabric/guide/checkpoint.rst#load-a-partial-checkpoint

> Loading a checkpoint is normally "strict", meaning parameter names in the checkpoint must match the parameter names in the model. However, when loading checkpoints for fine-tuning or transfer learning, it can happen that only a portion of the parameters match the model. For this case, you can disable strict loading to avoid errors:

```python
state = {"model": model}

# strict loading is the default
fabric.load("path/to/checkpoint.ckpt", state, strict=True)

# disable strict loading
fabric.load("path/to/checkpoint.ckpt", state, strict=False)
```
