### ISSUE TITLE
AttributeError: 'UnetSkipConnectionBlock' object has no attribute '1'

### ISSUE THREAD

**Issue by RohitDhankar** [RohitDhankar/Machine-Learning-with-Python_ML_Py#112]
- Testing code from the -- [pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)
```
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ python test.py --dataroot ./datasets/facades/testB --direction BtoA --model pix2pix --name facades_label2photo_pretrained --num_test 1
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 256                           
                 dataroot: ./datasets/facades/testB      	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 256                           
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: test]
               n_layers_D: 3                             
                     name: facades_label2photo_pretrained	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: batch                         
                 num_test: 1                             	[default: 50]
              num_threads: 4                             
                output_nc: 3                             
                    phase:                               
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
                use_wandb: False                         
                  verbose: False                         
       wandb_project_name: CycleGAN-and-pix2pix          
----------------- End -------------------
---INFO---opt.dataroot-- ./datasets/facades/testB
---INFO---opt.phase---  
---INFO---self.dir_AB-- ./datasets/facades/testB
dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints/facades_label2photo_pretrained/latest_net_G.pth
Traceback (most recent call last):
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/test.py", line 57, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 198, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 174, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 174, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/dhankar/anaconda3/envs/env2_det2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UnetSkipConnectionBlock' object has no attribute '1'
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
```

**Comment by RohitDhankar** [comment]
As suggested in prior issue on Source REPO - have added the Flag -- ```--netG resnet_9blocks```

```
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ python test.py --dataroot ./datasets/facades/testB --direction BtoA --model pix2pix --name facades_label2photo_pretrained --num_test 1 --netG resnet_9blocks
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 256                           
                 dataroot: ./datasets/facades/testB      	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 256                           
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: test]
               n_layers_D: 3                             
                     name: facades_label2photo_pretrained	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                	[default: unet_256]
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: batch                         
                 num_test: 1                             	[default: 50]
              num_threads: 4                             
                output_nc: 3                             
                    phase:                               
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
                use_wandb: False                         
                  verbose: False                         
       wandb_project_name: CycleGAN-and-pix2pix          
----------------- End -------------------
---INFO---opt.dataroot-- ./datasets/facades/testB
---INFO---opt.phase---  
---INFO---self.dir_AB-- ./datasets/facades/testB
dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints/facades_label2photo_pretrained/latest_net_G.pth
Traceback (most recent call last):
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/test.py", line 57, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 199, in load_networks
    net.load_state_dict(state_dict)
  File "/home/dhankar/anaconda3/envs/env2_det2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.2.weight", "model.2.bias", "model.5.weight", "model.5.bias", "model.8.weight", "model.8.bias", "model.10.conv_block.2.weight", "model.10.conv_block.2.bias", "model.10.conv_block.6.weight", "model.10.conv_block.7.weight", "model.10.conv_block.7.bias", "model.10.conv_block.7.running_mean", "model.10.conv_block.7.running_var", "model.11.conv_block.2.weight", "model.11.conv_block.2.bias", "model.11.conv_block.6.weight", "model.11.conv_block.7.weight", "model.11.conv_block.7.bias", "model.11.conv_block.7.running_mean", "model.11.conv_block.7.running_var", "model.12.conv_block.2.weight", "model.12.conv_block.2.bias", "model.12.conv_block.6.weight", "model.12.conv_block.7.weight", "model.12.conv_block.7.bias", "model.12.conv_block.7.running_mean", "model.12.conv_block.7.running_var", "model.13.conv_block.2.weight", "model.13.conv_block.2.bias", "model.13.conv_block.6.weight", "model.13.conv_block.7.weight", "model.13.conv_block.7.bias", "model.13.conv_block.7.running_mean", "model.13.conv_block.7.running_var", "model.14.conv_block.2.weight", "model.14.conv_block.2.bias", "model.14.conv_block.6.weight", "model.14.conv_block.7.weight", "model.14.conv_block.7.bias", "model.14.conv_block.7.running_mean", "model.14.conv_block.7.running_var", "model.15.conv_block.2.weight", "model.15.conv_block.2.bias", "model.15.conv_block.6.weight", "model.15.conv_block.7.weight", "model.15.conv_block.7.bias", "model.15.conv_block.7.running_mean", "model.15.conv_block.7.running_var", "model.16.conv_block.2.weight", "model.16.conv_block.2.bias", "model.16.conv_block.6.weight", "model.16.conv_block.7.weight", "model.16.conv_block.7.bias", "model.16.conv_block.7.running_mean", "model.16.conv_block.7.running_var", "model.17.conv_block.2.weight", "model.17.conv_block.2.bias", "model.17.conv_block.6.weight", "model.17.conv_block.7.weight", "model.17.conv_block.7.bias", "model.17.conv_block.7.running_mean", "model.17.conv_block.7.running_var", "model.18.conv_block.2.weight", "model.18.conv_block.2.bias", "model.18.conv_block.6.weight", "model.18.conv_block.7.weight", "model.18.conv_block.7.bias", "model.18.conv_block.7.running_mean", "model.18.conv_block.7.running_var", "model.20.weight", "model.20.bias", "model.23.weight", "model.23.bias". 
	Unexpected key(s) in state_dict: "model.1.bias", "model.4.bias", "model.7.bias", "model.10.conv_block.1.bias", "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.10.conv_block.6.num_batches_tracked", "model.11.conv_block.1.bias", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.11.conv_block.6.num_batches_tracked", "model.12.conv_block.1.bias", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.12.conv_block.6.num_batches_tracked", "model.13.conv_block.1.bias", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.13.conv_block.6.num_batches_tracked", "model.14.conv_block.1.bias", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.14.conv_block.6.num_batches_tracked", "model.15.conv_block.1.bias", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.15.conv_block.6.num_batches_tracked", "model.16.conv_block.1.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.16.conv_block.6.num_batches_tracked", "model.17.conv_block.1.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.17.conv_block.6.num_batches_tracked", "model.18.conv_block.1.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var", "model.18.conv_block.6.num_batches_tracked", "model.19.bias", "model.22.bias". 
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
```

**Comment by RohitDhankar** [comment]
probable solution -- refer -- https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/687

**Comment by RohitDhankar** [comment]
```



(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ python test.py --dataroot ./datasets/facades/testB --direction BtoA --model pix2pix --name facades_label2photo_pretrained
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
Warning: wandb package cannot be found. The option "--use_wandb" will result in error.
-[INFO]----class Pix2PixModel---modify_commandline_options-parser---- ArgumentParser(prog='test.py', usage=None, description=None, formatter_class=<class 'argparse.ArgumentDefaultsHelpFormatter'>, conflict_handler='error', add_help=True)
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 256                           
                 dataroot: ./datasets/facades/testB      	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 256                           
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: test]
               n_layers_D: 3                             
                     name: facades_label2photo_pretrained	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: batch                         
                 num_test: 50                            
              num_threads: 4                             
                output_nc: 3                             
                    phase:                               
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
                use_wandb: False                         
                  verbose: False                         
       wandb_project_name: CycleGAN-and-pix2pix          
----------------- End -------------------
---INFO---opt.dataroot-- ./datasets/facades/testB
---INFO---opt.phase---  
---INFO---self.dir_AB-- ./datasets/facades/testB
dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
-[INFO]---load_suffix---> latest
loading the model from ./checkpoints/facades_label2photo_pretrained/latest_net_G.pth
                              
-[INFO]---state_dict-KEY--->
 model.1.weight
-[INFO]---state_dict-KEY--->
 model.1.bias
-[INFO]---state_dict-KEY--->
 model.2.running_mean
-[INFO]---state_dict-KEY--->
 model.2.running_var
-[INFO]---state_dict-KEY--->
 model.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.4.weight
-[INFO]---state_dict-KEY--->
 model.4.bias
-[INFO]---state_dict-KEY--->
 model.5.running_mean
-[INFO]---state_dict-KEY--->
 model.5.running_var
-[INFO]---state_dict-KEY--->
 model.5.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.7.weight
-[INFO]---state_dict-KEY--->
 model.7.bias
-[INFO]---state_dict-KEY--->
 model.8.running_mean
-[INFO]---state_dict-KEY--->
 model.8.running_var
-[INFO]---state_dict-KEY--->
 model.8.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.10.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.10.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.10.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.10.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.10.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.10.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.10.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.10.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.10.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.10.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.11.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.11.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.11.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.11.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.11.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.11.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.11.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.11.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.11.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.11.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.12.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.12.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.12.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.12.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.12.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.12.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.12.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.12.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.12.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.12.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.13.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.13.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.13.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.13.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.13.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.13.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.13.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.13.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.13.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.13.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.14.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.14.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.14.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.14.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.14.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.14.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.14.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.14.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.14.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.14.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.15.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.15.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.15.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.15.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.15.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.15.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.15.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.15.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.15.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.15.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.16.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.16.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.16.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.16.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.16.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.16.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.16.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.16.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.16.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.16.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.17.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.17.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.17.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.17.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.17.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.17.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.17.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.17.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.17.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.17.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.18.conv_block.1.weight
-[INFO]---state_dict-KEY--->
 model.18.conv_block.1.bias
-[INFO]---state_dict-KEY--->
 model.18.conv_block.2.running_mean
-[INFO]---state_dict-KEY--->
 model.18.conv_block.2.running_var
-[INFO]---state_dict-KEY--->
 model.18.conv_block.2.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.18.conv_block.5.weight
-[INFO]---state_dict-KEY--->
 model.18.conv_block.5.bias
-[INFO]---state_dict-KEY--->
 model.18.conv_block.6.running_mean
-[INFO]---state_dict-KEY--->
 model.18.conv_block.6.running_var
-[INFO]---state_dict-KEY--->
 model.18.conv_block.6.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.19.weight
-[INFO]---state_dict-KEY--->
 model.19.bias
-[INFO]---state_dict-KEY--->
 model.20.running_mean
-[INFO]---state_dict-KEY--->
 model.20.running_var
-[INFO]---state_dict-KEY--->
 model.20.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.22.weight
-[INFO]---state_dict-KEY--->
 model.22.bias
-[INFO]---state_dict-KEY--->
 model.23.running_mean
-[INFO]---state_dict-KEY--->
 model.23.running_var
-[INFO]---state_dict-KEY--->
 model.23.num_batches_tracked
-[INFO]---state_dict-KEY--->
 model.26.weight
-[INFO]---state_dict-KEY--->
 model.26.bias
                                                                                          
Traceback (most recent call last):
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/test.py", line 57, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 89, in setup
    self.load_networks(load_suffix)
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 207, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 177, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/dhankar/temp/08_23/pytorch/cycle_gan/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 177, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/dhankar/anaconda3/envs/env2_det2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UnetSkipConnectionBlock' object has no attribute '1'
(env2_det2) dhankar@dhankar-1:~/.../pytorch-CycleGAN-and-pix2pix$ 





```


- Seems the issue will require the -- state_dict -- keys to be looked into  so this is the attempt for now 

```python
                state_dict = torch.load(load_path, map_location=str(self.device))
                print("   "*10)
                #print("--[INFO]--state_dict--->\n",state_dict) # DONT 
                for iter_key in list(state_dict.keys()):
                    print("-[INFO]---state_dict-KEY--->\n",iter_key)

                print("   "*30)

```

**Comment by RohitDhankar** [comment]
- ok RESOLVED - use the below terminal command with params as defined in the arguments being parsed , as seen below , ensure we have -- ```--no_dropout```
> python test.py --dataroot ./datasets/facades/testB --direction BtoA --model test --name facades_label2photo_pretrained --num_test 10 --no_dropout &> term_log_facades__09_16_2000h_4.log
