### ISSUE TITLE
TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'use_flash_attention_2'

### ISSUE THREAD

**Issue by RohitDhankar** [RohitDhankar/Machine-Learning-with-Python_ML_Py#125]
- terminal command as below 
- autotrain llm --train --project_name llm_1a --model abhishek/llama-2-7b-hf-small-shards --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft 

#

> got below error - even though the - ```use_flash_attention_2 = False``` , as seen below in the -- ```> INFO    Params: ```

```
> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='.', train_split='train', 
valid_split=None, text_column='text', model='abhishek/llama-2-7b-hf-small-shards', learning_rate=0.0002, 
num_train_epochs=3, train_batch_size=12, warmup_ratio=0.1, gradient_accumulation_steps=1, 
optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, 
add_eos_token=False, block_size=-1, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, 
logging_steps=-1, project_name='llm_1a', evaluation_strategy='epoch', save_total_limit=1, 
save_strategy='epoch', auto_find_batch_size=False, fp16=False, push_to_hub=False, use_int8=False, model_max_length=1024, 
repo_id=None, use_int4=True, trainer='sft', target_modules=None, merge_adapter=False, token=None, 
backend='default', username=None, use_flash_attention_2=False, func=<function run_llm_command_factory at 0x7fa70ed86520>)
> INFO    loading dataset from csv
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py", line 122, in train
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'use_flash_attention_2'

```

- terminal ERROR screenshot as below -- 

#

![Screenshot from 2023-10-02 18-42-21](https://github.com/RohitDhankar/Machine-Learning-with-Python_ML_Py/assets/13214169/c2ec7b00-c5c3-4b8e-ad5e-4d7b8780c9b5)

**Comment by RohitDhankar** [comment]
- 1st attempt at solution -- trying to install -- flash-attention , as mentioned here on this Transformers issue -- 
- https://github.com/huggingface/transformers/issues/26443

> this here is --flash-attention
- https://pypi.org/project/flash-attn/

#


```
env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ 
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ pip install packaging
Requirement already satisfied: packaging in /home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages (23.1)
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ 
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ pip uninstall -y ninja && pip install ninja
WARNING: Skipping ninja as it is not installed.
Collecting ninja
  Using cached ninja-1.11.1-py2.py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (145 kB)
Installing collected packages: ninja
Successfully installed ninja-1.11.1
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ 
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ pip install flash-attn --no-build-isolation
Collecting flash-attn
  Using cached flash_attn-2.3.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-36h435ml/flash-attn_24674599d8124136a0f94cd203770161/setup.py", line 19, in <module>
          from torch.utils.cpp_extension import (
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ pwd
/home/dhankar/temp/08_23/a___main_tutes_DL/a__LLM/Abhi_Thakur
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ 
(env_hface) dhankar@dhankar-1:~/.../Abhi_Thakur$ 
```

![Screenshot from 2023-10-02 19-08-01](https://github.com/RohitDhankar/Machine-Learning-with-Python_ML_Py/assets/13214169/f2d0b6e8-266c-4ea3-9495-063f55e276f5)

**Comment by RohitDhankar** [comment]
- solved -- as per comment by maintainer - had run the setup for -- 
- https://github.com/huggingface/autotrain-advanced/issues/284#issuecomment-1741238334

> $ autotrain setup &> term_log__setup__10_02__1930h__SETUPLogs__.log


#


```
> INFO    Installing latest transformers@main
> INFO    Successfully installed latest transformers
> INFO    Installing latest peft@main
> INFO    Successfully installed latest peft
> INFO    Installing latest diffusers@main
> INFO    Successfully installed latest diffusers
> INFO    Installing latest trl@main
> INFO    Successfully installed latest trl
> INFO    Installing latest xformers
> INFO    Successfully installed latest xformers
```

- now have CUDA out of memory issues due to the low end local GPU 
```
> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='.', train_split='train', valid_split=None, text_column='text', model='abhishek/llama-2-7b-hf-small-shards', learning_rate=0.0002, num_train_epochs=3, train_batch_size=12, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='llm_1a', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=False, push_to_hub=False, use_int8=False, model_max_length=1024, repo_id=None, use_int4=True, trainer='sft', target_modules=None, merge_adapter=False, token=None, backend='default', username=None, use_flash_attention_2=False, func=<function run_llm_command_factory at 0x7efbd041cc20>)
> INFO    loading dataset from csv
Loading the tokenizer from the `special_tokens_map.json` and the `added_tokens.json` will be removed in `transformers 5`,  it is kept for forward compatibility, but it is recommended to update your `tokenizer_config.json` by uploading it again. You will see the new `added_tokens_decoder` attribute that will store the relevant information.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Loading checkpoint shards:   0%|          | 0/10 [00:00<?, ?it/s]
Loading checkpoint shards:  10%|█         | 1/10 [00:35<05:22, 35.84s/it]
Loading checkpoint shards:  20%|██        | 2/10 [01:03<04:06, 30.85s/it]
Loading checkpoint shards:  30%|███       | 3/10 [01:29<03:20, 28.66s/it]
Loading checkpoint shards:  40%|████      | 4/10 [01:57<02:49, 28.31s/it]
Loading checkpoint shards:  50%|█████     | 5/10 [02:22<02:15, 27.18s/it]
Loading checkpoint shards:  60%|██████    | 6/10 [02:48<01:47, 26.93s/it]
Loading checkpoint shards:  70%|███████   | 7/10 [03:13<01:18, 26.29s/it]
Loading checkpoint shards:  70%|███████   | 7/10 [03:39<01:33, 31.31s/it]
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py", line 122, in train
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3303, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3691, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/modeling_utils.py", line 749, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/transformers/integrations/bitsandbytes.py", line 98, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 179, in to
    return self.cuda(device)
           ^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 157, in cuda
    w_4bit, quant_state = bnb.functional.quantize_4bit(w, blocksize=self.blocksize, compress_statistics=self.compress_statistics, quant_type=self.quant_type)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhankar/anaconda3/envs/env_hface/lib/python3.11/site-packages/bitsandbytes/functional.py", line 816, in quantize_4bit
    out = torch.zeros(((n+1)//2, 1), dtype=torch.uint8, device=A.device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 3.82 GiB total capacity; 2.98 GiB already allocated; 24.56 MiB free; 3.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
