### ISSUE TITLE
TypeError: '_asyncio.Future' object is not callable 

### ISSUE THREAD

**Issue by RohitDhankar** [RohitDhankar/Machine-Learning-with-Python_ML_Py#67]
- Sme issue as here -- https://github.com/tornadoweb/tornado/issues/3182
- But the code provided by -- doesnt work either - tried here with some edits of own -->  
- https://github.com/RohitDhankar/Machine-Learning-with-Python_ML_Py/blob/21f489a8cf6548d518500a4af20f1fc519785d15/dev_tornado/file_upload.py#L168

`(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
--GOT Filenames --- ['fl_2.txt']
HTTP PUT - Upload fl_2.txt:
Traceback (most recent call last):
  File "file_upload.py", line 202, in <module>
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 194, in main
    tasks.add(method(filenames))
TypeError: '_asyncio.Future' object is not callable
`

**Comment by RohitDhankar** [comment]
`dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
Traceback (most recent call last):
  File "file_upload.py", line 138, in <module>
    class Put(Task):
  File "file_upload.py", line 198, in Put
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 182, in main
    put_obj = Put()
NameError: name 'Put' is not defined
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
Traceback (most recent call last):
  File "file_upload.py", line 198, in <module>
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 182, in main
    put_obj = Put()
TypeError: __init__() missing 1 required positional argument: 'filenames'
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
--GOT Filenames --- ['fl_2.txt']
Traceback (most recent call last):
  File "file_upload.py", line 202, in <module>
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 186, in main
    put_obj = Put()
TypeError: __init__() missing 1 required positional argument: 'filenames'
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
--GOT Filenames --- ['fl_2.txt']
HTTP PUT - Upload fl_2.txt:
Traceback (most recent call last):
  File "file_upload.py", line 202, in <module>
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 194, in main
    tasks.add(method(filenames))
TypeError: '_asyncio.Future' object is not callable
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
(dbfs_env) dhankar@dhankar-1:~/.../torn$ 
`

**Comment by RohitDhankar** [comment]
`(dbfs_env) dhankar@dhankar-1:~/.../torn$ python file_upload.py --put fl_2.txt
--GOT Filenames --- ['fl_2.txt']
Traceback (most recent call last):
  File "file_upload.py", line 202, in <module>
    asyncio.run(main())
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dhankar/anaconda3/envs/dbfs_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "file_upload.py", line 186, in main
    put_obj = Put()
TypeError: __init__() missing 1 required positional argument: 'filenames'`

**Comment by RohitDhankar** [comment]
```python

async def main():
    """
    Returns
    -------
    None.

    """
    define("put", type=bool, help="Use PUT instead of POST", group="file uploader")

    # Tornado configures logging from command line opts and returns remaining args
    filenames = options.parse_command_line()
    
    
    if not filenames:
        print("Provide a list of filenames to upload.", file=sys.stderr)
        sys.exit(1)
    
    print("--GOT Filenames ---",filenames)
    put_obj = Put(filenames)
    post_obj = Post(filenames)

    method = put_obj.run() if options.put else post_obj.run()

    # Main coroutine, starting tasks:
    cond = asyncio.Condition()
    tasks = set()
    tasks.add(method(filenames))
    asyncio.gather(*(task.start(cond, tasks) for task in tasks))

    # Wait for the number of tasks to reach 0
    async with cond:
        await cond.wait_for(lambda: len(tasks) == 0)
        print("ALL TASKS are COMPLETED, EXITING.")

asyncio.run(main())


```
